import os
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from ucap.core.crypto_interface import CryptoPluginBase

class AESGCMPlugin(CryptoPluginBase):
    """
    AES-GCM Plugin for Phase-1.
    Uses session.sym_key for encryption/decryption.
    """

    id = "AES"

    def generate_keypair(self):
        """
        AES is symmetric → only one key.
        We return it as { 'key' : key } to keep API consistent.
        """
        key = AESGCM.generate_key(bit_length=256)
        return {"key": key}

    def encrypt(self, plaintext: bytes, session=None):
        """
        plaintext → AES-GCM ciphertext + nonce
        Uses session.sym_key (generated by SessionManager).
        """
        if session is None:
            raise ValueError("Session required for AES encryption")

        key = session.sym_key
        aes = AESGCM(key)
        nonce = os.urandom(12)

        ct = aes.encrypt(nonce, plaintext, None)

        return {
            "ciphertext": ct,
            "nonce": nonce
        }

    def decrypt(self, payload, session=None):
        """
        AES-GCM ciphertext → plaintext
        Expects payload = { 'ciphertext': ..., 'nonce': ... }
        """
        if session is None:
            raise ValueError("Session required for AES decryption")

        key = session.sym_key
        aes = AESGCM(key)

        nonce = payload["nonce"]
        ct = payload["ciphertext"]

        pt = aes.decrypt(nonce, ct, None)
        return pt
from ucap.core.crypto_interface import register_plugin
register_plugin(AESGCMPlugin())
